### ISSUE TITLE
Amelioration de l'user experience

### ISSUE THREAD

**Issue by Peltoche** [cozy-labs/partenariat-42#4]
Liste des améliorations a apporter:
- Général
  - Amélioration de l'affichage du compte pour savoir ou l'on est sur le site
  - Amélioration du wording
  - Localisation
- User
  - Affichage des informations suplementaires et options au passage de la sourie au dessus du nom des utilisateurs
- Archive
  - Afficher plus d'information dans le résumé d'une archive
- All-Count:
  - Affichage de plus d'informations
  - Format mobile: rétracter les détails de résumé du compte
- Count Modification
  - Choix d'une monnaie par défaut
- Count
  - Rendre tout les modules rétractables ?
  - Afficher les participants et de la personne ayant paye dans le header
- Create Count
  - Mettre une monnaie par défaut
- Config Général ?
  - Gestion d'une config général
  - Mettre une monnaie par défaut
  - Choisir quel module est rétracté ou non par défaut
  - Choisir les statistiques affiche

**Comment by Peltoche** [comment]
Faut il déplacer la gestion des utilisateurs (ajout) dans la section modification du compte?

**Comment by frankrousseau** [comment]
N'oubliez pas que c'est un projet pédagogique. Je ne suis pas sûr que les finitions UX sont importantes à ce stade.

**Comment by Peltoche** [comment]
Il est sur que l'on va pas tout implémenter, peut être les principaux si c'est rapide. Mais dans tout les cas il est toujours bon de faire une état des lieux et cela m'aideras a reprendre le projet si jamais je vois qu'il a du succee.

**Comment by frankrousseau** [comment]
Ok, je comprends mieux. Merci.
